### ISSUE TITLE
Missing heatshrink_decoder.h

### ISSUE THREAD

**Issue by jdunmire** [leon-anavi/esp8266-jadja#1]
I get this error when I try to build from a new clone:

``` C
...
CC user/espfs.c
user/espfs.c:50:32: fatal error: heatshrink_decoder.h: No such file or directory
 #include "heatshrink_decoder.h"
                                ^
compilation terminated.
```

I don't think it is a path problem since I can't find `heatshrink_deocder.h` anywhere in the source.

**Comment by leon-anavi** [comment]
Hi, ESP8266-jadja is based on esphttpd which makes use of heatshrink. It is a git submodule. To fetch the code do:

```
git submodule init
git submodule update
```

I will update the README with this information.

**Comment by leon-anavi** [comment]
The README has been updated. Please note that you will need to remove the include of stdint.h from lib/heatshrink/heatshrink_decoder.h if you get the following or similar error:

```
/opt/Espressif/ESP8266_SDK/include/stdint.h:83:5: warning: "TENSILICA" is not defined [-Wundef]
```

**Comment by jdunmire** [comment]
Thanks!
