### ISSUE TITLE
Great project

### ISSUE THREAD

**Issue by tinamore** [leon-anavi/esp8266-jadja#2]
Hi

This is a great project. Can you update with newest library from https://github.com/CHERTS/esp8266-devkit.

I hope you will always update this project, This is a great project for Iot.

How to add project and build flash from from Elipse Luna Windows 7 64bit ?

Thank you very much.

**Comment by leon-anavi** [comment]
Hi,

The Makefile of the project is integrated with Espressif SDK on my Ubuntu. For details: https://github.com/esp8266/esp8266-wiki/wiki/Toolchain

II don't have a computer with Windows therefore I am not interested in integration with Windows but I will be grad if someone makes a GitHub push request with changes that will allow both Linux and Windows users to build esp8266-jadja easily.

Thanks,
Leon

**Comment by tdmrhn** [comment]
It's a great project really but installing part is too difficult to any platform, will you make it a flash bin to install all platforms.

**Comment by leon-anavi** [comment]
Hi @adimavi, I am a Linux user and I don't have time to modify the Makefile for other platforms. I will be happy to merge your changes if you fix it for all platforms and send me GitHub pull request. Thanks, Leon
