### ISSUE TITLE
Recommendation: Include Instructions or Link to XTensa (Toolchain)

### ISSUE THREAD

**Issue by abrahamrhoffman** [leon-anavi/esp8266-jadja#3]
https://github.com/esp8266/esp8266-wiki/wiki/Toolchain#install-the-xtensa-crosstool-ng-as-local-user

Had to dig around to find it. :) Would be nice to include in the documentation so that others can build without getting errors such as:

$ make
CC driver/uart.c
make: xtensa-lx106-elf-gcc: Command not found
make: **\* [build/driver/uart.o] Error 127

Cause it's a pretty vague error.

Thanks to: http://www.esp8266.com/viewtopic.php?f=9&t=447 I was able to find that first link.

**Comment by leon-anavi** [comment]
Hi Abraham,

Thank you for the feedback. Your proposition is excellent I added a short description at the README with a link to the SDK installation guide.

Thanks,
Leon
