### ISSUE TITLE
HTML files are not compiling

### ISSUE THREAD

**Issue by Jigneshphulwaria** [leon-anavi/esp8266-jadja#4]
C:\Projects\esp8266\project\esp8266-jadja-master>make
AR build/httpd_app.a
LD build/httpd.out
FW firmware/0x00000.bin
FW firmware/0x40000.bin

C:\Projects\esp8266\project\esp8266-jadja-master>make htmlflash
make: **\* No rule to make target `html/', needed by`webpages.espfs'.  Stop.

I am compiling this project in windows environment. But getting the above error for htmlflash.Please help with this issue.
thank you

**Comment by leon-anavi** [comment]
H,

It works on my laptop with Ubuntu 15.04 but I think I see what might have caused the issue. 

Could please apply the following change to Makefile and report back the result?

```
diff --git a/Makefile b/Makefile
index b402fbf..d4abed3 100644
--- a/Makefile
+++ b/Makefile
@@ -145,7 +145,7 @@ flash: $(FW_FILE_1) $(FW_FILE_2)
        $(Q) $(ESPFLASH) --port $(ESPPORT) write_flash 0x00000 $(FW_FILE_1) 0x40000 $(FW_FILE_2)


-webpages.espfs: html/ mkespfsimage/mkespfsimage
+webpages.espfs: mkespfsimage/mkespfsimage
        cd html; find . | ../mkespfsimage/mkespfsimage > ../webpages.espfs; cd ..

 mkespfsimage/mkespfsimage: mkespfsimage/
```

Thanks,
Leon

**Comment by leon-anavi** [comment]
Hi, there was no further feedback on this issue so I will close it.
